api_data = [
    {
        "url": "https://supportive5741.zendesk.com/api/v2/tickets/1.json",
        "id": 1,
        "external_id": None,
        "via": {
            "channel": "sample_ticket",
            "source": {"from": {}, "to": {}, "rel": None},
        },
        "created_at": "2023-11-12T23:18:54Z",
        "updated_at": "2023-11-12T23:18:54Z",
        "generated_timestamp": 1699831134,
        "type": "incident",
        "subject": "Sample ticket: Meet the ticket",
        "raw_subject": "Sample ticket: Meet the ticket",
        "description": "Hi there,\n\nI’m sending an email because I’m having a problem setting up your new product. Can you help me troubleshoot?\n\nThanks,\n The Customer\n\n",
        "priority": "normal",
        "status": "open",
        "recipient": None,
        "requester_id": 22872158533139,
        "submitter_id": 22872142677139,
        "assignee_id": 22872142677139,
        "organization_id": None,
        "group_id": 22872165880595,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": ["sample", "support", "zendesk"],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "custom_status_id": 22872151107347,
        "followup_ids": [],
        "brand_id": 22872158286611,
        "allow_channelback": False,
        "allow_attachments": True,
        "from_messaging_channel": False,
    },
    {
        "url": "https://supportive5741.zendesk.com/api/v2/tickets/3.json",
        "id": 3,
        "external_id": None,
        "via": {
            "channel": "email",
            "source": {
                "from": {"address": "alviahmed06@gmail.com", "name": "Alvi Ahmed"},
                "to": {
                    "name": "Supportive",
                    "address": "support@supportive5741.zendesk.com",
                },
                "rel": None,
            },
        },
        "created_at": "2023-11-12T23:24:27Z",
        "updated_at": "2023-11-12T23:24:27Z",
        "generated_timestamp": 1699831468,
        "type": None,
        "subject": "Hey",
        "raw_subject": "Hey",
        "description": "Hi, \n\nThis is a test",
        "priority": None,
        "status": "open",
        "recipient": "support@supportive5741.zendesk.com",
        "requester_id": 22872142677139,
        "submitter_id": 22872142677139,
        "assignee_id": 22872142677139,
        "organization_id": 22872158312979,
        "group_id": 22872165880595,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": [],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "custom_status_id": 22872151107347,
        "followup_ids": [],
        "brand_id": 22872158286611,
        "allow_channelback": False,
        "allow_attachments": True,
        "from_messaging_channel": False,
    },
    {
        "url": "https://supportive5741.zendesk.com/api/v2/tickets/5.json",
        "id": 5,
        "external_id": None,
        "via": {
            "channel": "email",
            "source": {
                "from": {"address": "alviahmed06@gmail.com", "name": "Alvi Ahmed"},
                "to": {
                    "name": "Supportive",
                    "address": "support@supportive5741.zendesk.com",
                },
                "rel": None,
            },
        },
        "created_at": "2023-11-12T23:32:48Z",
        "updated_at": "2023-11-12T23:33:08Z",
        "generated_timestamp": 1699831989,
        "type": None,
        "subject": "Again, I need help",
        "raw_subject": "Again, I need help",
        "description": "My account is locked after I tried logging in with the wrong password several times",
        "priority": None,
        "status": "open",
        "recipient": "support@supportive5741.zendesk.com",
        "requester_id": 22872142677139,
        "submitter_id": 22872142677139,
        "assignee_id": 22872142677139,
        "organization_id": 22872158312979,
        "group_id": 22872165880595,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": [],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "custom_status_id": 22872151107347,
        "followup_ids": [],
        "brand_id": 22872158286611,
        "allow_channelback": False,
        "allow_attachments": True,
        "from_messaging_channel": False,
    },
    {
        "url": "https://supportive5741.zendesk.com/api/v2/tickets/6.json",
        "id": 6,
        "external_id": None,
        "via": {
            "channel": "email",
            "source": {
                "from": {"address": "alviahmed06@gmail.com", "name": "Alvi Ahmed"},
                "to": {
                    "name": "Supportive",
                    "address": "support@supportive5741.zendesk.com",
                },
                "rel": None,
            },
        },
        "created_at": "2023-11-12T23:34:05Z",
        "updated_at": "2023-11-12T23:34:17Z",
        "generated_timestamp": 1699832058,
        "type": None,
        "subject": "error",
        "raw_subject": "error",
        "description": "I keep getting an error saying 'Incorrect username or email.",
        "priority": None,
        "status": "open",
        "recipient": "support@supportive5741.zendesk.com",
        "requester_id": 22872142677139,
        "submitter_id": 22872142677139,
        "assignee_id": 22872142677139,
        "organization_id": 22872158312979,
        "group_id": 22872165880595,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": [],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "custom_status_id": 22872151107347,
        "followup_ids": [],
        "brand_id": 22872158286611,
        "allow_channelback": False,
        "allow_attachments": True,
        "from_messaging_channel": False,
    },
    {
        "url": "https://supportive5741.zendesk.com/api/v2/tickets/7.json",
        "id": 7,
        "external_id": None,
        "via": {
            "channel": "email",
            "source": {
                "from": {"address": "alviahmed06@gmail.com", "name": "Alvi Ahmed"},
                "to": {
                    "name": "Supportive",
                    "address": "support@supportive5741.zendesk.com",
                },
                "rel": None,
            },
        },
        "created_at": "2023-11-12T23:35:03Z",
        "updated_at": "2023-11-12T23:36:22Z",
        "generated_timestamp": 1699832185,
        "type": None,
        "subject": "2 factor broken",
        "raw_subject": "2 factor broken",
        "description": "I'm not receiving the two-factor authentication code on my phone.",
        "priority": None,
        "status": "pending",
        "recipient": "support@supportive5741.zendesk.com",
        "requester_id": 22872142677139,
        "submitter_id": 22872142677139,
        "assignee_id": 22872142677139,
        "organization_id": 22872158312979,
        "group_id": 22872165880595,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": [],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "custom_status_id": 22872165874963,
        "followup_ids": [],
        "brand_id": 22872158286611,
        "allow_channelback": False,
        "allow_attachments": True,
        "from_messaging_channel": False,
    },
    {
        "url": "https://supportive5741.zendesk.com/api/v2/tickets/8.json",
        "id": 8,
        "external_id": None,
        "via": {
            "channel": "email",
            "source": {
                "from": {"address": "alviahmed06@gmail.com", "name": "Alvi Ahmed"},
                "to": {
                    "name": "Supportive",
                    "address": "support@supportive5741.zendesk.com",
                },
                "rel": None,
            },
        },
        "created_at": "2023-11-12T23:37:10Z",
        "updated_at": "2023-11-12T23:37:45Z",
        "generated_timestamp": 1699832265,
        "type": None,
        "subject": "this is shite",
        "raw_subject": "this is shite",
        "description": "I'm entering the correct 2FA code, but it keeps saying it's invalid. What's going on?",
        "priority": None,
        "status": "open",
        "recipient": "support@supportive5741.zendesk.com",
        "requester_id": 22872142677139,
        "submitter_id": 22872142677139,
        "assignee_id": 22872142677139,
        "organization_id": 22872158312979,
        "group_id": 22872165880595,
        "collaborator_ids": [],
        "follower_ids": [],
        "email_cc_ids": [],
        "forum_topic_id": None,
        "problem_id": None,
        "has_incidents": False,
        "is_public": True,
        "due_at": None,
        "tags": [],
        "custom_fields": [],
        "satisfaction_rating": None,
        "sharing_agreement_ids": [],
        "custom_status_id": 22872151107347,
        "followup_ids": [],
        "brand_id": 22872158286611,
        "allow_channelback": False,
        "allow_attachments": True,
        "from_messaging_channel": False,
    },
]


